name: Java CI with Gradle

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  gradle_build:
    strategy:
      matrix:
        os: [ macos-13, macos-14, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew clean build
