# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Package Distribution Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: false
        default: 1.0.0-SNAPSHOT

permissions:
  contents: read

jobs:
  package_app:
    strategy:
      matrix:
        configuration: [
          { runner: "macos-13", path: "build/dist/*" },
          { runner: "macos-14", path: "build/dist/*" },
          { runner: "windows-2022", path: "build/dist/*" }
        ]
    runs-on: ${{ matrix.configuration.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Package app with Gradle
        run: ./gradlew jpackage
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gem_${{ runner.os }}-${{ runner.arch }}_${{ github.ref_name }}-${{ github.sha }}
          path: ${{ matrix.configuration.path }}